### ISSUE TITLE
Blog Link Redirect Issue

### ISSUE THREAD

**Issue by mypablo** [vanguardvirtual/repo-ranger#7] opened 2024-09-15 13:04 UTC
### **Description:**
When a user's blog link does not include the scheme (i.e., `'https://'` or `'http://'`), the redirect fails to work correctly. This issue occurs if the link is entered as just `www.google.com` or `google.com`, leading to an incomplete redirect.

### **Steps to Reproduce:**
1. Go to a user's profile with a blog URL that doesn't include `http://` or `https://`.
2. Click on the blog link in the user profile.
3. Observe that the redirect does not occur successfully.

### **Expected Behavior:**
The blog link should redirect properly, even if the URL doesn't include the scheme (`http://` or `https://`). The URL should be normalized automatically.

### **Screenshots:**
1. **Before clicking the blog link:**
   ![screenshot-1](https://github.com/user-attachments/assets/c2d92d7f-1963-4fc2-bb83-7a8e413d0835)

2. **After clicking the blog link (incorrect redirect):**
   ![screenshot-2](https://github.com/user-attachments/assets/aa10e89d-d7e1-40fb-8f6b-5ec606b9e0a1)

### **Additional Context:**
This issue occurs because the scheme is not included in the URL, causing the browser to handle the link incorrectly. A possible fix would be to normalize the URL by prepending `http://` or `https://` if it's missing.

**Comment by AkisKourouklis** [comment] 2024-09-16 04:43
Thanks for mentioning this issue @mypablo I am currently looking into it.

**Comment by AkisKourouklis** [comment] 2024-09-16 05:09
The issue is now fixed and closed with this commit ([abc2a71](https://github.com/vanguardvirtual/repo-ranger/commit/abc2a717e5311bbafe8730bc3063aa3ee88f8285)). 

Thanks a lot @mypablo for finding and mentioning this issue

**Closed by AkisKourouklis** 2024-09-16 05:09 UTC
Labels: bug
